name: Maven Package Build

# Trigger the workflow on push to master branch
on:
  push:
    branches:
      - master

# Define the job
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 17 environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Java 17
          distribution: 'temurin' # Use Temurin JDK (recommended)

      # Cache Maven dependencies for faster builds
      - name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven package build
      - name: Build with Maven
        run: mvn clean package
